package com.entidad;
// Generated 21-nov-2015 9:14:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private Integer idUsuarios;
     private String usuarios;
     private String clave;
     private String nombre;
     private String apellido;
     private boolean eliminar;
     private Set compras = new HashSet(0);

    public Usuarios() {
    }

	
    public Usuarios(String usuarios, String clave, String nombre, String apellido, boolean eliminar) {
        this.usuarios = usuarios;
        this.clave = clave;
        this.nombre = nombre;
        this.apellido = apellido;
        this.eliminar = eliminar;
    }
    public Usuarios(String usuarios, String clave, String nombre, String apellido, boolean eliminar, Set compras) {
       this.usuarios = usuarios;
       this.clave = clave;
       this.nombre = nombre;
       this.apellido = apellido;
       this.eliminar = eliminar;
       this.compras = compras;
    }
   
    public Integer getIdUsuarios() {
        return this.idUsuarios;
    }
    
    public void setIdUsuarios(Integer idUsuarios) {
        this.idUsuarios = idUsuarios;
    }
    public String getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(String usuarios) {
        this.usuarios = usuarios;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public boolean isEliminar() {
        return this.eliminar;
    }
    
    public void setEliminar(boolean eliminar) {
        this.eliminar = eliminar;
    }
    public Set getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set compras) {
        this.compras = compras;
    }




}


